---
- name: others | master | upload certificates to the cluster with kubeadm
  command: kubeadm init phase upload-certs --experimental-upload-certs
  delegate_to: "{{ cluster_name }}-kube-master.service.automium.consul"
  register: kubeadm_certficate_key

- name: others | master | DEBUG generated certificate key for debug
  debug:
    var: kubeadm_certficate_key.stdout_lines[2]

- name: others | master | generate create token with ttl 5m
  command: kubeadm token create --ttl 5m
  delegate_to: "{{ cluster_name }}-kube-master.service.automium.consul"
  register: kubeadm_token

- name: others | master | generate join command for master
  command: kubeadm token create --ttl 60m
  delegate_to: "{{ cluster_name }}-kube-master.service.automium.consul"
  register: kubeadm_join_command

- name: others | master | render kubeadm configuration for join controlplane
  template:
    src: templates/kubeadm/kubeadm.master.join.yml.j2
    dest: "/etc/kubernetes/kubeadm-conf.yml"
    owner: root
    group: root
    mode: 0600

- name: rsync remote cert
  fetch:
    src: "/etc/kubernetes/pki/ca.crt"
    dest: "/etc/kubernetes/pki/ca.crt"
    flat: yes

- name: rsync remote cert
  fetch:
    src: "/etc/kubernetes/pki/ca.key"
    dest: "/etc/kubernetes/pki/ca.key"
    flat: yes

- name: rsync remote cert
  fetch:
    src: "/etc/kubernetes/pki/ca.key"
    dest: "/etc/kubernetes/pki/ca.key"
    flat: yes

- name: rsync remote cert
  fetch:
    src: "/etc/kubernetes/pki/etcd/ca.crt"
    dest: "/etc/kubernetes/pki/etcd/ca.crt"
    flat: yes

- name: rsync remote cert
  fetch:
    src: "/etc/kubernetes/pki/etcd/ca.key"
    dest: "/etc/kubernetes/pki/etcd/ca.key"
    flat: yes

- name: other | master | upgrade | generate certificates
  command: kubeadm join phase control-plane-prepare certs --config /etc/kubernetes/kubeadm-conf.yml
  register: kubeadm_join_phase_control-plane-prepare_certs

- name: other | master | upgrade | control-plane-prepare kubeconfig 
  command: kubeadm join phase control-plane-prepare kubeconfig --config /etc/kubernetes/kubeadm-conf.yml
  register: kubeadm_join_phase_control-plane-prepare_certs 

- name: other | master | upgrade | control-plane-prepare kubeconfig 
  command: kubeadm join phase control-plane-prepare control-plane --config /etc/kubernetes/kubeadm-conf.yml
  register: kubeadm_join_phase_control-plane-prepare_certs

- name: Synchronization of src on the control machine to dest on the remote hosts
  synchronize:
    src: /etc/kubernetes/ssl/
    dest: /etc/kubernetes/pki/

- fail:
    msg: The system may not be provisioned according to the CMDB status.
  when: cmdb_status != "to-be-staged"