---
- name: others | master | postconfigure | check calico version
  command: calicoctl version
  register: calico_version_row

- name: others | master | postconfigure | Debug Message
  set_fact:
    calico_cluster_version: '{{ item.split(":") | map("trim") | list | reject("search","Cluster Version")|list | join }}'
  with_items: "{{ calico_version_row.stdout_lines|select('search','Cluster Version')|list }}"

- name: others | master | postconfigure | Debug show calico version
  debug:
    var: calico_cluster_version
