---
- name: others | master | pre_task | check ETCD cluster for remove useless member
  command: /usr/local/bin/etcd-scripts/remove-etcd --etcd-host={{ cluster_name }}-etcd.service.automium.consul:2379  --cluster-ip-check={{ ansible_default_ipv4.address }} --cluster-host-check {{ ansible_hostname }}
  register: remove_etcd
  delegate_to: "{{ cluster_name }}-etcd.service.automium.consul"

- name: others | master | pre_task | show remove_etcd stdout
  debug:
    var: remove_etcd.stdout

- name: others | master | pre_task | cleanup ETCD lib folder
  file:
    path: /var/lib/etcd
    state: absent
