---
stages:
- test-infra
- build-service-container
- build-release-service-container
- build-image
- build-release-image

after_script:
  - docker volume prune -f


run-molecule:
  image: automium/molecule:2.22-bionic
  stage: test-infra
  script:
  - bash cicd/test.sh
  only:
  - master
  - tags

build-service-container:
  image: automium/molecule:2.22-bionic
  stage: build-service-container
  script:
  - bash cicd/container.sh
  only:
    refs:
      - master
    changes:
      - config.tf.tmpl
      - tasks/image.yml

build-release-service-container:
  image: automium/molecule:2.22-bionic
  stage: build-service-container
  script:
  - bash cicd/container.sh
  only:
    - tags

build-image:
  image: automium/buildenv:bionic
  stage: build-image
  script:
  - bash cicd/build.sh
  only:
    refs:
      - master
    changes:
      - config.tf.tmpl
      - tasks/image.yml

build-release-image:
  image: automium/buildenv:bionic
  stage: build-image
  script:
  - bash cicd/build.sh
  only:
    - tags