---
- name: configure | ssh config
  template:
    src: ssh_config
    dest: /root/.ssh/config

- name: configure | render cloud configurations
  template:
    src: "templates/provider/{{ cloud_provider }}/cloud.conf.j2"
    dest: /etc/kubernetes/cloud.conf
    owner: root
    group: root
    mode: 0600
  when: provider != "none"

- name: configure | ensure Docker service is started
  service:
    name: docker
    state: started

- name: configure | configure filebeat
  include_role:
    name: entercloudsuite.filebeat
    public: yes
  vars:
    add_repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    filebeat_pakage: filebeat=7.4.2
    filebeat_conf:
      output.elasticsearch:
        hosts: ["http://10.2.0.12:9200"]
    filebeat_enable_modules:
      - system
    filebeat_enabled: true
    filebeat_state: started
