---
- name: configure | ssh config
  template:
    src: ssh_config
    dest: /root/.ssh/config

- name: configure | render cloud configurations
  template:
    src: "templates/provider/{{ cloud_provider }}/cloud.conf.j2"
    dest: /etc/kubernetes/cloud.conf
    owner: root
    group: root
    mode: 0600
  when: provider != "none"

- name: configure | ensure Docker service is started
  service:
    name: docker
    state: started
