---
- name: import pretask {{ cluster_role }}
  import_tasks: all/{{ cluster_role }}/pre_task_configure.yml

- name: configure | ssh config
  template:
    src: ssh_config.j2
    dest: /root/.ssh/config

- name: configure | render cloud configurations
  template:
    src: "templates/provider/{{ cloud_provider }}/cloud.conf.j2"
    dest: /etc/kubernetes/cloud.conf
    owner: root
    group: root
    mode: 0600
  when: provider != "none"

- name: configure | ensure Docker service is started
  service:
    name: docker
    state: started

- name: configure | configure filebeat
  include_role:
    name: entercloudsuite.filebeat
    public: yes
  vars:
    add_repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    filebeat_pakage: filebeat=7.4.2
    filebeat_conf:
      output.elasticsearch:
        hosts:
          - "{{ filebeat_es_url }}"
        protocol: "https"
        path: "{{ filebeat_es_path }}"
        username: "{{ filebeat_es_user }}"
        password: "{{ filebeat_es_pass }}"
      setup.ilm.enabled: false
      setup.dashboards.enabled: false
    filebeat_enable_modules:
      - system
    filebeat_enabled: true
    filebeat_state: started
  when: filebeat_es_url | length > 0
