---
- name: vars | print env variable cluster_name
  debug:
    var: cluster_name

- name: vars | print env name
  debug:
    var: name

- name: set_vars init_role to others
  set_fact:
    init_role: others
  tags: others

- name: set_vars init_role to bootstrap
  set_fact:
    init_role: bootstrap
  tags: bootstrap

- name: vars | print env init_role
  debug:
    var: init_role

- name: set_vars cluster_role to master
  set_fact:
    cluster_role: "master"
  when: master == "true"

- name: set_vars cluster_role to node
  set_fact:
    cluster_role: "node"
  when: node == "true"

- name: vars | print env cluster_role
  debug:
    var: cluster_role
