---
- name: all | master | post_task | consul service account
  copy:
    src: kubernetes/consul_cluster_rolebinding.yaml
    dest: /tmp/consul_cluster_rolebinding.yaml

- name: all | master | post_task | deploy script for create consul kube_config
  copy:
    src: scripts/consul_kubectl.sh
    dest: /tmp/consul_kubectl.sh
    owner: root
    group: root
    mode: 0700

- name: all | master | post_task | create kubeconfig for consul
  command: /tmp/consul_kubectl.sh

- name: all | master | post_task | restart consul for reload check
  service:
    name: consul
    state: restarted
