---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: automium-autoscaler-restarter
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs:
    - get
    - patch
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-node-remover
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs:
    - get
    - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-node-check
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-node-check-rb
subjects:
- kind: ServiceAccount
  name: consul-node-check
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-autoscaler-restarter-rb
subjects:
- kind: ServiceAccount
  name: consul-node-check
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: automium-autoscaler-restarter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-node-remover-rb
subjects:
- kind: ServiceAccount
  name: consul-node-check
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: consul-node-remover
  apiGroup: rbac.authorization.k8s.io
