---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: testcluster-testcluster-0
    dataVolume: testcluster-master-data
  - name: testcluster-testworker-0
    dataVolume: testcluster-worker-data
provisioner:
  name: ansible
  options:
    diff: True
    v: True
    e: test_env=true
  playbooks:
    create: create.yml
    destroy: destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - syntax
