---
- name: prepare SSH service
  hosts: all
  gather_facts: False
  tasks:
  - name: regenerate host keys
    command: dpkg-reconfigure openssh-server
  - name: prepare ssh directory
    file:
       path: /root/.ssh
       owner: root
       group: root
       mode: 0700
       state: directory
  - name: move test ssh key on right places in test instances
    copy:
       src: "{{ item.src }}"
       dest: "{{ item.dst }}"
       remote_src: yes
       owner: root
       group: root
       mode: 0600
    with_items:
       - { src: /usr/src/cloud/roles/service-kubernetes/testkey.pem, dst: /root/.ssh/id_rsa }
       - { src: /usr/src/cloud/roles/service-kubernetes/testkey.pem.pub, dst: /root/.ssh/authorized_keys }
  - name: restart ssh service
    service:
       name: ssh
       state: restarted

- name: test role wrapper
  hosts: all
  strategy: free
  tasks:
     - name: launch the test playbook on the remote master instance
       command: >-
         ansible-playbook -i 127.0.0.1
         --skip-tags others
         --extra-vars 'testmode="true" master="true" node="false" etcd="true"
         cluster_name="testcluster" identity="testcluster-ci" image="kubernetes-ci-test" provider="none"'
         /usr/src/cloud/roles/service-kubernetes/molecule/default/playbook.test.yml
       args:
          chdir: /usr/src/cloud
       environment:
          ANSIBLE_ROLES_PATH: ":/tmp/:/usr/src/cloud/roles"
          CONSUL: "consul.service.automium.consul"
          CONSUL_DATACENTER: "automium"
          CONSUL_PORT: "8500"
          CONSUL_ENCRYPT: "A2+WhqBtZjsA5tLlpOOmBXoTprRFMWnc+N5beexyZiM="
          SERVICE: "automium/service-kubernetes"
       when: ansible_hostname == "testcluster-testcluster-0"
     - name: launch the test playbook on the remote worker instance
       command: >-
         ansible-playbook -i 127.0.0.1
         --skip-tags bootstrap
         --extra-vars 'testmode="true" master="false" node="true" etcd="false"
         cluster_name="testcluster" pool_name="testpool" identity="testcluster-ci" image="kubernetes-ci-test" provider="none"
         rancher_url="" rancher_cluster_token = ""
         '
         /usr/src/cloud/roles/service-kubernetes/molecule/default/playbook.test.yml
       args:
          chdir: /usr/src/cloud
       environment:
          ANSIBLE_ROLES_PATH: ":/tmp/:/usr/src/cloud/roles"
          CONSUL: "consul.service.automium.consul"
          CONSUL_DATACENTER: "automium"
          CONSUL_PORT: "8500"
          CONSUL_ENCRYPT: "A2+WhqBtZjsA5tLlpOOmBXoTprRFMWnc+N5beexyZiM="
          SERVICE: "automium/service-kubernetes"
       when: ansible_hostname == "testcluster-testworker-0"
