---
- name: others | all | make sure the master service is resolvable
  command: "dig +short {{ cluster_name }}-kube-master.service.automium.consul"
  register: resolve_command
  retries: 100
  delay: 3
  until: resolve_command.stdout != ""
  failed_when: resolve_command.stdout == ""

- include_tasks: helpers/generate_calico.yml
  vars:
    delegate_host_for_cert_generations: "{{ cluster_name }}-kube-master.service.automium.consul"
    server_conf:
      CN: Server
      hosts:
        - 127.0.0.1
        - localhost
        - "{{ ansible_hostname }}"
        - "{{ ansible_fqdn }}"
      key:
        algo: rsa
        size: 2048

- name: others | all | include configure role for "{{ cluster_role }}"
  include: "{{ init_role }}/configure-{{ cluster_role }}.yml"
  static: no

- name: others | all | add preflight ignore in test
  set_fact:
    join_command: "{{ join_command }} --ignore-preflight-errors=all"
  when:
    - testmode == "true"

- name: others | all | show join command
  debug:
    var: join_command

- name: configure other | execute the generated join command
  command: "{{ join_command }}"
