---
- name: helpers | generate calico | DEBUG show host delegate for cert generations
  debug:
    var: delegate_host_for_cert_generations

- name: helpers | generate calico | Create /etc/calico dir
  file:
    state: directory
    path: /etc/calico

- name: helpers | generate calico | create calico /etc/calico/pki certs
  file:
    state: directory
    path: /etc/calico/pki

- name: show servr conf vars
  debug:
    var: server_conf

- name: debug
  shell: echo $SERVER | cfssl gencert -ca=/etc/kubernetes/pki/etcd/ca.crt -ca-key=/etc/kubernetes/pki/etcd/ca.key -config=/etc/cfssl/etcd/certificate.json -profile=client -
  environment:
    SERVER: "{{ server_conf | to_json }}"
  register: cfssl_out
  delegate_to: "{{ delegate_host_for_cert_generations }}"

- name: from json
  set_fact:
    cfssl_clean: "{{ cfssl_out.stdout | from_json }}"

- name: show vars with shell
  shell: echo $CFSSL_OUT
  environment:
    CFSSL_OUT: "{{ cfssl_clean | to_json }}"
  register: out

- name: vars
  debug:
    var: cfssl_clean

- name: copy
  copy:
    content: "{{ cfssl_clean }}"
    dest: /etc/calico/cert.json

- name: create certificates
  shell: |
   cat /etc/calico/cert.json | cfssljson -bare node-calico
   rm -rfv /etc/calico/cert.json
  args:
    chdir: /etc/calico/pki

- name: Copy etcd ca.cert
  fetch:
    src: /etc/kubernetes/pki/etcd/ca.crt
    dest: /etc/calico/pki/ca.crt
    flat: yes
  delegate_to: "{{ delegate_host_for_cert_generations }}"
